apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: migrate
        image: postgres:15-alpine
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: POSTGRES_PASSWORD
        command:
        - sh
        - -c
        - |
          psql -h postgresql -U postgres -d db -c "
          CREATE TABLE IF NOT EXISTS accounts (
            ID INT PRIMARY KEY,
            Amount INT NOT NULL DEFAULT 0
          );
          CREATE TABLE IF NOT EXISTS users (
            ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            Name VARCHAR(64) UNIQUE,
            Password VARCHAR(512) NOT NULL
          );
          CREATE TABLE IF NOT EXISTS orders (
            ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            UserID INT NOT NULL,
            Amount INT NOT NULL,
            Status VARCHAR(16) NOT NULL
          );
          CREATE TABLE IF NOT EXISTS notifications (
            ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
            UserID INT NOT NULL,
            Text VARCHAR(512) NOT NULL
          );
          "
      restartPolicy: OnFailure