apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
data:
  DB_USER: "postgres"
  DB_HOST: "postgresql"
  DB_NAME: "db"
  DB_PORT: "5432"
  APP_PORT: "8080"
  JWT_SECRET: "myJwtSecretSample"
  BILLING_SVC_PORT: "80"